// SPDX-License-Identifier: Apache-2.0

export { adaptSourceManifestForExplainer } from './adapter'
export { canonicalRecord, shortHash, stableSourceId } from './id'
export { normalizeSourceCaptureManifest } from './normalize'
export {
  domSafetyIssue,
  inlineAssetSafetyIssue,
  isSafeLocalKey,
  isSafeProjectPath,
  isSafeRoutePath,
  normalizeProjectPath,
  remoteAssetUrlIssue,
  styleSafetyIssue,
} from './safety'
export {
  SourceManifestValidationError,
  assertValidSourceCaptureManifest,
  resolveSourceManifestLimits,
  validateSourceCaptureManifest,
} from './validate'
export {
  SOURCE_CAPTURE_LIMITS,
  type ExplainerDemoGuidance,
  type ExplainerDemoGuidanceStep,
  type ExplainerSourcePackage,
  type NormalizeSourceManifestOptions,
  type NormalizedSourceAsset,
  type NormalizedSourceComponent,
  type NormalizedSourceComponentOccurrence,
  type NormalizedSourceComponentVariant,
  type NormalizedSourceDomNode,
  type NormalizedSourceInteraction,
  type NormalizedSourceManifest,
  type NormalizedSourceProject,
  type NormalizedSourceRoute,
  type NormalizedSourceScreen,
  type NormalizedSourceScreenState,
  type NormalizedSourceStyleSnapshot,
  type SourceAssetInput,
  type SourceAssetKind,
  type SourceAssetLocationInput,
  type SourceCaptureManifestInput,
  type SourceComponentBoundaryInput,
  type SourceDomNodeInput,
  type SourceFramework,
  type SourceInteractionAction,
  type SourceInteractionInput,
  type SourceInteractionStateKind,
  type SourceManifestIssue,
  type SourceManifestIssueCode,
  type SourceManifestLimits,
  type SourceManifestStats,
  type SourceManifestValidationResult,
  type SourceOriginKind,
  type SourceProjectInput,
  type SourceProvenance,
  type SourceProvenanceInput,
  type SourceRouteInput,
  type SourceScreenInput,
  type SourceScreenStateInput,
  type SourceStyleSnapshotInput,
  type SourceViewport,
} from './types'
